"""initial 11 tables

Revision ID: 12e2f6296660
Revises: 
Create Date: 2026-05-01 18:29:02.528261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12e2f6296660'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('business_number', sa.String(length=20), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.Enum('TRIAL', 'ACTIVE', 'PAUSED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('subscription_started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lounges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('LOUNGE', 'REST_AREA', name='loungetype'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('facility_shower', sa.Boolean(), nullable=False),
    sa.Column('facility_sleep_room', sa.Boolean(), nullable=False),
    sa.Column('facility_laundry', sa.Boolean(), nullable=False),
    sa.Column('facility_restaurant', sa.Boolean(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('sido', sa.String(length=50), nullable=True),
    sa.Column('sigungu', sa.String(length=50), nullable=True),
    sa.Column('road_name', sa.String(length=100), nullable=True),
    sa.Column('operating_hours', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('DRIVER', 'COMPANY_ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('truck_type', sa.Enum('TRUCK_5T', 'TRUCK_11T', 'TRUCK_25T', 'TRAILER', name='trucktype'), nullable=True),
    sa.Column('voice_tone', sa.String(length=20), nullable=False),
    sa.Column('consent_location', sa.Boolean(), nullable=False),
    sa.Column('consent_microphone', sa.Boolean(), nullable=False),
    sa.Column('consent_dtg', sa.Boolean(), nullable=False),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.Enum('SPOUSE', 'SON', 'DAUGHTER', 'MOTHER', 'FATHER', 'OTHER', name='relationship'), nullable=True),
    sa.Column('phone_encrypted', sa.String(length=500), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('auto_notification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.String(length=2000), nullable=True),
    sa.Column('refresh_token_encrypted', sa.String(length=2000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_uid')
    )
    op.create_table('personal_info',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('real_name_encrypted', sa.String(length=500), nullable=True),
    sa.Column('phone_encrypted', sa.String(length=500), nullable=True),
    sa.Column('email_encrypted', sa.String(length=500), nullable=True),
    sa.Column('encryption_key_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('total_duration_min', sa.Integer(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.Column('rest_count', sa.Integer(), nullable=False),
    sa.Column('risk_alert_l1_count', sa.Integer(), nullable=False),
    sa.Column('risk_alert_l2_count', sa.Integer(), nullable=False),
    sa.Column('risk_alert_l3_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companion_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=True),
    sa.Column('utterance', sa.String(length=2000), nullable=False),
    sa.Column('intent', sa.Enum('DROWSY', 'LONELY', 'INFO_LOUNGE', 'FAMILY_MSG', 'EMERGENCY', 'GENERAL', name='intent'), nullable=True),
    sa.Column('response', sa.String(length=2000), nullable=False),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('claude_model', sa.String(length=50), nullable=True),
    sa.Column('claude_tokens_in', sa.Integer(), nullable=True),
    sa.Column('claude_tokens_out', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drowsiness_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.Column('lstm_score', sa.Float(), nullable=True),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('final_level', sa.Enum('L0', 'L1', 'L2', 'L3', name='drowsinesslevel'), nullable=False),
    sa.Column('user_response', sa.Enum('ACCEPTED', 'DECLINED', name='userresponse'), nullable=True),
    sa.Column('nearest_lounge_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['nearest_lounge_id'], ['lounges.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('family_contact_id', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.Enum('DEPARTURE', 'REST', 'ARRIVAL', 'EMERGENCY', name='messagetype'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('delivery_method', sa.String(length=20), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'MOCK', name='deliverystatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_contact_id'], ['family_contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_notifications')
    op.drop_table('drowsiness_assessments')
    op.drop_table('companion_conversations')
    op.drop_table('trips')
    op.drop_table('personal_info')
    op.drop_table('oauth_accounts')
    op.drop_table('family_contacts')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('lounges')
    op.drop_table('companies')
    # ### end Alembic commands ###
